# NUMPY Documentation

In [ ]:
import numpy as np

In [36]:
#defining an array
#Syntax --> variable_name = np.array([])

Matrix_A=np.array([[1,2,3],[4,5,6],[7,8,9]])
Matrix_B=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(Matrix_A)
print(Matrix_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#get dimensions of the matrix
#Syntax --> Variable_name.ndim
#here variable_name is name of the matrix
Matrix_A.ndim
#dimension means 1D, 2D, 3D, ....,nD matrix is it

2

In [38]:
#Get shape of the matrix
#this gives the number of rows and columns in a matrix (r,c)
#Syntax --> Variable_name.shape
Matrix_A.shape

(3, 3)

In [39]:
#Matrix_A.nbytes

In [40]:
#get a specific number
#Syntax --> Variable_name[r,c] 
#indexing in python starts from zero.
#this is acually a function returning a value.
Matrix_A[2,2]

9

In [41]:
#Get a specific number from the array
#and we mumtiple want to print the number then 
print(Matrix_A[0,2])
print(Matrix_A[1,1])
print(Matrix_A[2,0])

3
5
7


In [42]:
#get a specific row
#Syntax --> variable_name = [r,:]
Matrix_A[1,:]

array([4, 5, 6])

In [43]:
#get a specific row
#Syntax --> variable_name = [:,c]
Matrix_A[:,0]

array([1, 4, 7])

In [51]:
#if we want a specific row from which we need numbers in a range 
Matrix_B[0, 1:6:2]
#in the above the matrix 
# '1' is actually the index of the matrix in that row and '6' is the "n+1" index in the same row
#goto Zeroth row in which get the range from 1 to 6 and step by 2

array([2, 4, 6])

In [53]:
#want to change the element at a specific position
Matrix_A[1,2]=100
print(Matrix_A)

[[  1   2   3]
 [  4   5 100]
 [  7   8   9]]


In [57]:
#want to change the multiple element of the matrix in a single syntax
Matrix_A[2,:]=3
print(Matrix_A)
print("\n")
Matrix_A[0,:] = [13,23,33]
print(Matrix_A)

[[ 13  23  33]
 [  4   5 100]
 [  3   3   3]]


[[ 13  23  33]
 [  4   5 100]
 [  3   3   3]]


In [74]:
Matrix_C=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
#in the above matrix their are 2 sets of 2x2 matrix
print(Matrix_C)
#this is a 3D matrix
print(Matrix_C.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [75]:
print(Matrix_C[0,1,1])
#the above syntax says that go to the Zeroth List
print("\n")
print(Matrix_C[:,1,:])
#the above syntax says that go to each of the 2x2 matrix take the 2nd row(row-index=1) and all the column


4


[[3 4]
 [7 8]]


In [76]:
#now if you want to replace multiple element in Matrix_C
Matrix_C[:,1,:]=[[17,17],[18,18]]
print(Matrix_C)
print("\n")
Matrix_C[1,0,1]=122
print(Matrix_C)

[[[ 1  2]
  [17 17]]

 [[ 5  6]
  [18 18]]]


[[[  1   2]
  [ 17  17]]

 [[  5 122]
  [ 18  18]]]


### initializing different types of array

In [81]:
#matrix of all zeros
print(np.zeros((2,3)))
print("\n")
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [85]:
#matrix  full of any other number

np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

### Basic Mathematics in the array and the matrix

In [92]:
print(Matrix_A)
print("\n")
Matrix_A = Matrix_A + 2 #likewise all the operations such as +,-,*,/,%
print(Matrix_A)
print("\n")
#lets say we want Sine values of all the elements 
np.sin(Matrix_A)

[[ 17  27  37]
 [  8   9 104]
 [  7   7   7]]


[[ 19  29  39]
 [ 10  11 106]
 [  9   9   9]]




array([[ 0.14987721, -0.66363388,  0.96379539],
       [-0.54402111, -0.99999021, -0.7271425 ],
       [ 0.41211849,  0.41211849,  0.41211849]])

#### --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

### Linear Algebra in the array and the matrix

In [104]:
#matrix Multiplication 
# syntax --> 'import library'Variable-Name.matmul(Matrix1,Matrix2,....)
Matrix1 = np.full((2,3),4)
print(Matrix1)
Matrix2 = np.full((3,4),2)
print('\n')
print(Matrix2)
print('\n')
c = np.matmul(Matrix1,Matrix2)
print(Matrix3)

[[4 4 4]
 [4 4 4]]


[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


[[24 24 24 24]
 [24 24 24 24]]


In [107]:
np.max(Matrix_A)

106